Fix for empty code fences
When there's an empty code fence, polytexnic breaks:

```
/usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/polytexnic-0.9.3/lib/polytexnic/utils.rb:209:in `add_font_info': undefined method `gsub!' for nil:NilClass (NoMethodError)
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/polytexnic-0.9.3/lib/polytexnic/utils.rb:141:in `block (2 levels) in highlight_source_code'
...
```

To replicate, I'm just doing something like:

```ruby
```